services:
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./web:/rails
      - log:/rails/log
      - storage:/rails/storage
      - tmp:/rails/tmp
    environment:
      RAILS_ENV: development
    command: /rails/bin/rails server -b 0.0.0.0
    networks:
      - app-network

  watsxn:
    build:
      context: ./watsxn
    ports:
      - "5000:5000"
    # depends_on:
    #   - postgres
    volumes:
      - ./watsxn:/app
      - log:/app/log
      - storage:/app/storage
      - tmp:/app/tmp
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - watsxn
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: tom96da
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: tom96da
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  log:
  storage:
  tmp:

networks:
  app-network:
    driver: bridge
